### ISSUE TITLE
Error: Can't find the sensor name in entity

### ISSUE THREAD

**Issue by gafk** [xguitoux/lovelace-bosch-indego-card#5]
Trying to setup the card, I am getting the error "Can't find the sensor name in entity". Anything I am doing wrong?

![grafik](https://user-images.githubusercontent.com/72245547/180591261-20789d46-69d6-4e3c-8530-b6695b7b6893.png)

Here is my setup of the mower (in configuration.yaml):

```
indego:
  username: !secret indego_username
  password: !secret indego_password
  id: !secret indego_id
  name: "DR Rasenmaher"

```

And the entitiy setup (via UI):

![grafik](https://user-images.githubusercontent.com/72245547/180591323-af80acc2-cd56-4b31-ba08-d32e89c865da.png)
